server:
  port: 12121
spring:
  profiles:
    active: local
  cloud:
    gateway:
      globalcors:
        cors-configurations:
            '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                - OPTIONS
                - HEAD
                allowedHeaders:
                - "*"
                #allowCredentials: true
      routes:
        - id: dispatch
          uri: error://localhost
          predicates:
            - Path=/**
          filters:
            - ProxyFilterFactory
logging:
  level:
    org.jetlinks: debug
proxy:
  frp:
    cmd: /home/user/frpc
    server-address: "127.0.0.1"
    server-port: 7000
    token: token
    server-ports: "7001-7010"